# Generated by Django 4.2.5 on 2023-09-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'PRoducto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
