# Generated by Django 4.2.5 on 2023-09-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_alter_producto_options_producto_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólar estadounidense'), ('EUR', 'Euros'), ('ARS', 'Pesos Argentinos'), ('BRL', 'Reales Argentinos')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
