# Generated by Django 4.2.5 on 2023-09-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_alter_producto_options_producto_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Tienda'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólar estadounidense'), ('EUR', 'Euros'), ('ARS', 'Pesos Argentinos'), ('BRL', 'Reales')], max_length=3),
        ),
    ]
