# Generated by Django 4.2 on 2023-11-10 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosextra',
            options={'verbose_name': 'Dato Extra', 'verbose_name_plural': 'Datos Extras'},
        ),
    ]
