# Generated by Django 4.2 on 2023-11-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0002_alter_datosextra_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosextra',
            name='biografia',
            field=models.CharField(max_length=30000),
        ),
    ]
